"""Initial Migration

Revision ID: 6b2a270172b1
Revises: 
Create Date: 2024-05-28 00:20:45.692695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2a270172b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linked_in_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('linkedin_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linkedin_id')
    )
    op.create_table('linked_in_liker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('linkedin_user_id', sa.String(length=120), nullable=False),
    sa.Column('liker_user_name', sa.String(length=120), nullable=False),
    sa.Column('liker_user_id', sa.String(length=120), nullable=False),
    sa.Column('post_id', sa.String(length=200), nullable=False),
    sa.Column('likers_title', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['linkedin_user_id'], ['linked_in_user.linkedin_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linked_in_liker')
    op.drop_table('linked_in_user')
    # ### end Alembic commands ###
